version: '3.7'
services:
  frontend: 
    build: 
      context: .
      dockerfile: Dockerfile.dev
    container_name: anam-earth-fe-dev
    ports: 
      - "3000:3000"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true
    tty: true
